### PR TITLE
Patch 4: New Black Hole Image, Missing Moons of Gas Giants, and an Additional To-Do List Amidst Testing and Merge Conflict Challenges

### PR DESCRIPTION
**Pull request by BraveCaperCat2**
Patch 4 adds a black hole image, the moons of jupiter, saturn and uranus which were left out in mainstream updates (which are gravitationally rounded) and another todo list (really? well you already have 2 todo lists... what's a third?)

Patch 4 could not be tested due to an environment issue:
Hi! I'm having an issue right now where if I launch the game, none of the changes I've made since I last successfully tested (during the development of Patch 3) have had no effect on the game in any way. The only thing I've changed since then is that I installed github desktop - I was using the website UI previously. Please help.

There is at least one merge conflict which I could not solve (github desktop doesn't seem to have an option for that, which is the whole reason I downloaded it) and is a file conflict as I add a new technology while you move the technology code to another file.

### CODE REVIEW

**Comment by BraveCaperCat2** [comment]
I will resolve the line conflicts.

**Comment by PlexPt** [comment]
I can help you

**Comment by PlexPt** [comment]
I send you msg at dicord

**Comment by BraveCaperCat2** [comment]
Also I forgot to add technologies for the new moons, and locale - I fixed the locale issue while fixing the merge commits.

**Comment by PlexPt** [comment]
I use IDEA for development and Git for version control, which is very convenient.

**Comment by BraveCaperCat2** [comment]
> > I use IDEA for development and Git for version control, which is very convenient.
> 
> Ah. I use vscode for development - and had been using github desktop for version control. VSCode was asking me to install git though, so now I've done that and am removing github desktop. How do you merge your commits from the local repo to the remote repo and back? Github desktop did that for me with a single click each.

Wait, VSCode wanted to be signed into github. Seems that might be to automatically merge to and from the remote repo.
I'll have to test it to see if it works - I mean, the issues only started happening after installing github desktop.

**Comment by BraveCaperCat2** [comment]
Ready for merging!

**Pull request merged**
